// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_humidValue;
extern lv_obj_t * ui_tempValue;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_dateValue;
extern lv_obj_t * ui_timeValue;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_awsValue;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_sensorerrorValue;
extern lv_obj_t * ui_inteneterrorValue;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_humidValue1;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_tempOffsetLabel;
extern lv_obj_t * ui_tempOffsetValue;
extern lv_obj_t * ui_tempOffsetMinus;
extern lv_obj_t * ui_tempOffsetMinusLabel;
extern lv_obj_t * ui_tempOffsetPlus;
extern lv_obj_t * ui_tempOffsetPlusLabel;
extern lv_obj_t * ui_humidOffsetLabel;
extern lv_obj_t * ui_humidOffsetValue;
extern lv_obj_t * ui_humidOffsetMinus;
extern lv_obj_t * ui_humidOffsetMinusLabel;
extern lv_obj_t * ui_humidOffsetPlus;
extern lv_obj_t * ui_humidOffsetPlusLabel;
// CUSTOM VARIABLES

// EVENTS
void ui_event_Screen1(lv_event_t * e);
void ui_event_Screen2(lv_event_t * e);
void ui_event_TempOffsetMinus(lv_event_t * e);
void ui_event_TempOffsetPlus(lv_event_t * e);
void ui_event_HumidOffsetMinus(lv_event_t * e);
void ui_event_HumidOffsetPlus(lv_event_t * e);

extern lv_obj_t * ui____initial_actions0;

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
