// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void ui_event_Screen1(lv_event_t * e);
void ui_event_Screen2(lv_event_t * e);
void ui_event_TempOffsetMinus(lv_event_t * e);
void ui_event_TempOffsetPlus(lv_event_t * e);
void ui_event_HumidOffsetMinus(lv_event_t * e);
void ui_event_HumidOffsetPlus(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
