// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_add_flag(ui_Screen2, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_set_style_bg_color(ui_Screen2, lv_color_hex(0x292929), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_navToScreen1 = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_navToScreen1, 32);
    lv_obj_set_height(ui_navToScreen1, 32);
    lv_obj_set_align(ui_navToScreen1, LV_ALIGN_TOP_LEFT);
    lv_obj_set_x(ui_navToScreen1, 6);
    lv_obj_set_y(ui_navToScreen1, 6);
    lv_obj_add_event_cb(ui_navToScreen1, ui_event_GotoScreen1, LV_EVENT_CLICKED, NULL);
    lv_obj_set_style_bg_color(ui_navToScreen1, lv_color_hex(0x3A3A3A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_navToScreen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_navToScreen1Label = lv_label_create(ui_navToScreen1);
    lv_label_set_text(ui_navToScreen1Label, LV_SYMBOL_LEFT);
    lv_obj_center(ui_navToScreen1Label);
    lv_obj_set_style_text_color(ui_navToScreen1Label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_navToScreen1Label, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_angle(ui_navToScreen1Label, -900, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tempOffsetLabel = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_tempOffsetLabel, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_tempOffsetLabel, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_tempOffsetLabel, 60);
    lv_obj_set_y(ui_tempOffsetLabel, -70);
    lv_obj_set_align(ui_tempOffsetLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_tempOffsetLabel, "Temp Offset (°C)");
    lv_obj_set_style_text_color(ui_tempOffsetLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_tempOffsetLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_tempOffsetLabel, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_angle(ui_tempOffsetLabel, -900, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tempOffsetValue = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_tempOffsetValue, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_tempOffsetValue, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_tempOffsetValue, 110);
    lv_obj_set_y(ui_tempOffsetValue, -20);
    lv_obj_set_align(ui_tempOffsetValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_tempOffsetValue, "0.0");
    lv_obj_set_style_text_color(ui_tempOffsetValue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_tempOffsetValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_tempOffsetValue, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_angle(ui_tempOffsetValue, -900, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tempOffsetMinus = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_tempOffsetMinus, 48);
    lv_obj_set_height(ui_tempOffsetMinus, 48);
    lv_obj_set_x(ui_tempOffsetMinus, 60);
    lv_obj_set_y(ui_tempOffsetMinus, 40);
    lv_obj_set_align(ui_tempOffsetMinus, LV_ALIGN_CENTER);
    lv_obj_add_event_cb(ui_tempOffsetMinus, ui_event_TempOffsetMinus, LV_EVENT_CLICKED, NULL);
    lv_obj_set_style_bg_color(ui_tempOffsetMinus, lv_color_hex(0x3A3A3A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_tempOffsetMinus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tempOffsetMinusLabel = lv_label_create(ui_tempOffsetMinus);
    lv_label_set_text(ui_tempOffsetMinusLabel, "-");
    lv_obj_center(ui_tempOffsetMinusLabel);
    lv_obj_set_style_text_color(ui_tempOffsetMinusLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_tempOffsetMinusLabel, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_angle(ui_tempOffsetMinusLabel, -900, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tempOffsetPlus = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_tempOffsetPlus, 48);
    lv_obj_set_height(ui_tempOffsetPlus, 48);
    lv_obj_set_x(ui_tempOffsetPlus, 140);
    lv_obj_set_y(ui_tempOffsetPlus, 40);
    lv_obj_set_align(ui_tempOffsetPlus, LV_ALIGN_CENTER);
    lv_obj_add_event_cb(ui_tempOffsetPlus, ui_event_TempOffsetPlus, LV_EVENT_CLICKED, NULL);
    lv_obj_set_style_bg_color(ui_tempOffsetPlus, lv_color_hex(0x3A3A3A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_tempOffsetPlus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tempOffsetPlusLabel = lv_label_create(ui_tempOffsetPlus);
    lv_label_set_text(ui_tempOffsetPlusLabel, "+");
    lv_obj_center(ui_tempOffsetPlusLabel);
    lv_obj_set_style_text_color(ui_tempOffsetPlusLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_tempOffsetPlusLabel, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_angle(ui_tempOffsetPlusLabel, -900, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_humidOffsetLabel = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_humidOffsetLabel, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_humidOffsetLabel, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_humidOffsetLabel, -60);
    lv_obj_set_y(ui_humidOffsetLabel, -70);
    lv_obj_set_align(ui_humidOffsetLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_humidOffsetLabel, "Humidity Offset (%)");
    lv_obj_set_style_text_color(ui_humidOffsetLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_humidOffsetLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_humidOffsetLabel, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_angle(ui_humidOffsetLabel, -900, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_humidOffsetValue = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_humidOffsetValue, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_humidOffsetValue, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_humidOffsetValue, -10);
    lv_obj_set_y(ui_humidOffsetValue, -20);
    lv_obj_set_align(ui_humidOffsetValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_humidOffsetValue, "0.0");
    lv_obj_set_style_text_color(ui_humidOffsetValue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_humidOffsetValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_humidOffsetValue, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_angle(ui_humidOffsetValue, -900, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_humidOffsetMinus = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_humidOffsetMinus, 48);
    lv_obj_set_height(ui_humidOffsetMinus, 48);
    lv_obj_set_x(ui_humidOffsetMinus, -140);
    lv_obj_set_y(ui_humidOffsetMinus, 40);
    lv_obj_set_align(ui_humidOffsetMinus, LV_ALIGN_CENTER);
    lv_obj_add_event_cb(ui_humidOffsetMinus, ui_event_HumidOffsetMinus, LV_EVENT_CLICKED, NULL);
    lv_obj_set_style_bg_color(ui_humidOffsetMinus, lv_color_hex(0x3A3A3A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_humidOffsetMinus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_humidOffsetMinusLabel = lv_label_create(ui_humidOffsetMinus);
    lv_label_set_text(ui_humidOffsetMinusLabel, "-");
    lv_obj_center(ui_humidOffsetMinusLabel);
    lv_obj_set_style_text_color(ui_humidOffsetMinusLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_humidOffsetMinusLabel, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_angle(ui_humidOffsetMinusLabel, -900, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_humidOffsetPlus = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_humidOffsetPlus, 48);
    lv_obj_set_height(ui_humidOffsetPlus, 48);
    lv_obj_set_x(ui_humidOffsetPlus, -60);
    lv_obj_set_y(ui_humidOffsetPlus, 40);
    lv_obj_set_align(ui_humidOffsetPlus, LV_ALIGN_CENTER);
    lv_obj_add_event_cb(ui_humidOffsetPlus, ui_event_HumidOffsetPlus, LV_EVENT_CLICKED, NULL);
    lv_obj_set_style_bg_color(ui_humidOffsetPlus, lv_color_hex(0x3A3A3A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_humidOffsetPlus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_humidOffsetPlusLabel = lv_label_create(ui_humidOffsetPlus);
    lv_label_set_text(ui_humidOffsetPlusLabel, "+");
    lv_obj_center(ui_humidOffsetPlusLabel);
    lv_obj_set_style_text_color(ui_humidOffsetPlusLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_humidOffsetPlusLabel, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_angle(ui_humidOffsetPlusLabel, -900, LV_PART_MAIN | LV_STATE_DEFAULT);
}
